ARDMK_DIR = /home/knight/git/Arduino-Makefile
AVRDUDE_CONF = /usr/share/arduino/hardware/tools/avrdude.conf
AVRDUDE = /usr/bin/avrdude
ARDUINO_LIBS = ros_lib SDL_Arduino_INA3221 Wire lib
AVR_TOOLS_DIR=/usr
ARDUION_DIR = /usr/share/arduino
ARDUION_PORT = /dev/ttyUSB*
USER_LIB_PATH = /home/knight/git/knightbot/libraries
BOARD_TAG = mega2560
include /home/knight/git/Arduino-Makefile/Arduino.mk

