// Generated by gencpp from file master_node/motors.msg
// DO NOT EDIT!


#ifndef MASTER_NODE_MESSAGE_MOTORS_H
#define MASTER_NODE_MESSAGE_MOTORS_H

#include <ros/service_traits.h>


#include <master_node/motorsRequest.h>
#include <master_node/motorsResponse.h>


namespace master_node
{

struct motors
{

typedef motorsRequest Request;
typedef motorsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct motors
} // namespace master_node


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::master_node::motors > {
  static const char* value()
  {
    return "1dc0bbce23ad0191e8ff5d2a2e5aa5e7";
  }

  static const char* value(const ::master_node::motors&) { return value(); }
};

template<>
struct DataType< ::master_node::motors > {
  static const char* value()
  {
    return "master_node/motors";
  }

  static const char* value(const ::master_node::motors&) { return value(); }
};


// service_traits::MD5Sum< ::master_node::motorsRequest> should match 
// service_traits::MD5Sum< ::master_node::motors > 
template<>
struct MD5Sum< ::master_node::motorsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::master_node::motors >::value();
  }
  static const char* value(const ::master_node::motorsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::master_node::motorsRequest> should match 
// service_traits::DataType< ::master_node::motors > 
template<>
struct DataType< ::master_node::motorsRequest>
{
  static const char* value()
  {
    return DataType< ::master_node::motors >::value();
  }
  static const char* value(const ::master_node::motorsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::master_node::motorsResponse> should match 
// service_traits::MD5Sum< ::master_node::motors > 
template<>
struct MD5Sum< ::master_node::motorsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::master_node::motors >::value();
  }
  static const char* value(const ::master_node::motorsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::master_node::motorsResponse> should match 
// service_traits::DataType< ::master_node::motors > 
template<>
struct DataType< ::master_node::motorsResponse>
{
  static const char* value()
  {
    return DataType< ::master_node::motors >::value();
  }
  static const char* value(const ::master_node::motorsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MASTER_NODE_MESSAGE_MOTORS_H
