// Generated by gencpp from file master_node/motorsRequest.msg
// DO NOT EDIT!


#ifndef MASTER_NODE_MESSAGE_MOTORSREQUEST_H
#define MASTER_NODE_MESSAGE_MOTORSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace master_node
{
template <class ContainerAllocator>
struct motorsRequest_
{
  typedef motorsRequest_<ContainerAllocator> Type;

  motorsRequest_()
    : cmd(0)
    , param(0)  {
    }
  motorsRequest_(const ContainerAllocator& _alloc)
    : cmd(0)
    , param(0)  {
  (void)_alloc;
    }



   typedef int32_t _cmd_type;
  _cmd_type cmd;

   typedef int32_t _param_type;
  _param_type param;





  typedef boost::shared_ptr< ::master_node::motorsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::master_node::motorsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct motorsRequest_

typedef ::master_node::motorsRequest_<std::allocator<void> > motorsRequest;

typedef boost::shared_ptr< ::master_node::motorsRequest > motorsRequestPtr;
typedef boost::shared_ptr< ::master_node::motorsRequest const> motorsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::master_node::motorsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::master_node::motorsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace master_node

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::master_node::motorsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::master_node::motorsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::master_node::motorsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::master_node::motorsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::master_node::motorsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::master_node::motorsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::master_node::motorsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "03abd4ee53c484dbb0c0a6a2c61970c4";
  }

  static const char* value(const ::master_node::motorsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x03abd4ee53c484dbULL;
  static const uint64_t static_value2 = 0xb0c0a6a2c61970c4ULL;
};

template<class ContainerAllocator>
struct DataType< ::master_node::motorsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "master_node/motorsRequest";
  }

  static const char* value(const ::master_node::motorsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::master_node::motorsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 cmd\n\
int32 param\n\
";
  }

  static const char* value(const ::master_node::motorsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::master_node::motorsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cmd);
      stream.next(m.param);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct motorsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::master_node::motorsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::master_node::motorsRequest_<ContainerAllocator>& v)
  {
    s << indent << "cmd: ";
    Printer<int32_t>::stream(s, indent + "  ", v.cmd);
    s << indent << "param: ";
    Printer<int32_t>::stream(s, indent + "  ", v.param);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MASTER_NODE_MESSAGE_MOTORSREQUEST_H
