ARDMK_DIR = /home/machy/git/Arduino-Makefile
AVRDUDE_CONF = /usr/share/arduino/hardware/tools/avrdude.conf
AVRDUDE = /usr/bin/avrdude
ARDUINO_LIBS =  SDL_Arduino_INA3221 Wire lib Adafruit_VL53L0X
AVR_TOOLS_DIR=/usr
ARDUION_DIR = /usr/share/arduino
ARDUION_PORT = /dev/ttyUSB*
USER_LIB_PATH = /home/machy/git2/knightbot/libraries
BOARD_TAG = mega2560
include /home/machy/git/Arduino-Makefile/Arduino.mk

